drop table if exists ss_task;
drop table if exists ss_enterprise;
drop table if exists ss_subject;
drop table if exists ss_user;

--企业用户
create table ss_enterprise (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	password varchar(255) not null,
	email varchar(64) not null,
	salt varchar(64) not null,
	enterprise_name varchar(255) not null unique,
	org_attribute varchar(32) not null,
	address varchar(255) not null,
	scale varchar(64) not null,
	business_cover varchar(32) not null,
	business_type varchar(64) not null,
	contacts varchar(32) not null,
	id_num varchar(32) not null,
	mobile varchar(32) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

create table ss_subject (
	id bigint generated by default as identity,
	name varchar(128) not null,
	description varchar(255),
	enterprise_id bigint not null,
    primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	create_date timestamp not null,
	enterprise_id bigint not null,
	primary key (id)
);

CREATE TABLE IF NOT EXISTS ss_questions (
  id bigint generated by default as identity,
  questiontype int(3) NOT NULL,
  question text NOT NULL,
  questionuserid int(11) NOT NULL,
  questionusername varchar(120) NOT NULL,
  questionlastmodifyuser varchar(120) NOT NULL,
  questionselect text NOT NULL,
  questionselectnumber tinyint(11) NOT NULL,
  questionanswer text NOT NULL,
  questiondescribe text NOT NULL,
  questioncreatetime int(11) NOT NULL,
  questionlevel int(1) NOT NULL,
  PRIMARY KEY (id)
);